### ISSUE TITLE
task-service-example: ping response is not compatible 

### ISSUE THREAD

**Issue by Surbhi-sharma1** [sourcefuse/loopback4-microservice-catalog#1760] opened 2023-10-17 05:52 UTC
While building task service example  getting the following error:

.

![Screenshot from 2023-10-16 14-31-47](https://github.com/sourcefuse/loopback4-microservice-catalog/assets/98279679/b39471a8-02d6-44f4-80b7-788d76b1f363)

.

**Comment by rahulvsf** [comment] 2023-11-06 03:58
This already seems to be fixed by someone else. I could not reproduce this error. `start` command -
![image](https://github.com/sourcefuse/loopback4-microservice-catalog/assets/127078920/5f0d4db3-e2b8-4e16-b795-643aca6c28e2)

**Comment by yeshamavani** [comment] 2023-11-07 05:55
@Surbhi-sharma1 can you verify

**Comment by Surbhi-sharma1** [comment] 2023-11-08 07:15
yes ,its working now

**Closed** 2023-11-08 07:15 UTC

**Comment by Surbhi-sharma1** [comment] 2023-11-16 11:45
fixed with PR #
https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1684
