### ISSUE TITLE
Change password only support changing password for internal auth provider

### ISSUE THREAD

**Issue by sumit-singhania** [sourcefuse/loopback4-microservice-catalog#1999] opened 2024-02-20 09:21 UTC
**Describe the bug**
Change password API only support changing password of internal auth-provider only which causes issue when you have multiple auth-provider and you have to keep track of all auth-provider.
In that case this API work only for internal auth provider for remaining auth-provider it give error

**To Reproduce**
1. Instead of internal auth-provider set auth-provider for any other provider like key clock or cognito
2. Try to change password for user who have been registered through these auth providers except internal
3. You will get error indicating invalid client or provider as check is specific in internal provider

**Expected behavior**
It should be able to change password based on auth-provider for that user we have if token and auth-provider detail matches.
**Screenshots**

**Additional context**
It should not have hardcoded check for internal user as auth-provider it should be dynamic like if the user is valid than based on auth-provider if valid is present than it should be able to logout

**Comment by yeshamavani** [comment] 2024-04-09 14:33
Since we dont save passwords of other auth providers, we dont have an option to change the passwords either 
that can be done directly at the auth providers end 
This request is not compliant hence closing

**Closed by yeshamavani** 2024-04-09 14:33 UTC
Labels: multitenancy

**Comment by samarpan-b** [comment] 2024-04-09 14:34
This is a duplicate of #1998
