### ISSUE TITLE
@soruceloop/cli: RepositoryMixin and ServiceMixin missing while creating any kind of service

### ISSUE THREAD

**Issue by dev-hitesh-gupta** [sourcefuse/loopback4-microservice-catalog#933] opened 2022-08-03 09:47 UTC
**Describe the bug**
RepositoryMixin and ServiceMixin missing while creating service using @soruceloop/cli

**To Reproduce**
1. create any type of service using @sourceloop/cli
2. go to applicatio.ts
3. check for Mixins

**Expected behavior**
There should be RepositoryMixin and ServiceMixin as they come while doing the lb4 app

**Comment by yeshamavani** [comment] 2022-10-11 07:16
@dev-hitesh-gupta  as discussed not able to reproduce and also there is no change in to logic of declaring and defining the application class.

Tried the cases where a service is based upon a sourceloop service and also an individual one.
![image](https://user-images.githubusercontent.com/83634146/195020649-a916fe80-58a6-40e0-af5b-f7d27f6c844e.png)

![image](https://user-images.githubusercontent.com/83634146/195020732-db8da0de-10b2-40b3-ad2b-bce653092b26.png)


Closing this issue for now.. in case issue still persists feel free to reopen or create a new one.

**Closed by yeshamavani** 2022-10-11 07:16 UTC
