### ISSUE TITLE
Add support for node 18 

### ISSUE THREAD

**Issue by yeshamavani** [sourcefuse/loopback4-microservice-catalog#1371] opened 2023-04-07 06:06 UTC
**Describe the bug**
Add support for node 18 in all our services. and remove the ones we dont support eg. 12

**Description**
Cuurently most of the services give support only till node 16 but we should include it till node 18. 

**To Reproduce**
1. Check the package.json files of specific services

**Expected behavior**
Node 18 should be supported.

**Comment by shubhamp-sf** [comment] 2023-04-07 06:56
Duplicate of https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1359

**Closed by shubhamp-sf** 2023-04-07 06:56 UTC
