### ISSUE TITLE
Export feature in Audit Service

### ISSUE THREAD

**Issue by gautam23-sf** [sourcefuse/loopback4-microservice-catalog#1324] opened 2023-02-21 09:31 UTC
**Is your feature request related to a problem? Please describe.**
To export the audit logs.

**Describe the solution you'd like**
Export feature is added in Audit Service using extensions.

**Comment by shubhamp-sf** [comment] 2023-07-02 08:46
Duplicate of https://github.com/sourcefuse/loopback4-microservice-catalog/issues/1449

**Closed by shubhamp-sf** 2023-07-02 08:46 UTC
